// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_PERMISSION_PLUS_API_G_H_
#define PIGEON_PERMISSION_PLUS_API_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace permission_plus_windows {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const ::flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const ::flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  ::flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class PermissionPlusHostApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};


// Mirror of `PermissionType` from `permission_plus_platform_interface`.
enum class PermissionTypeMessage {
  kCamera = 0,
  kMicrophone = 1,
  kPhotos = 2,
  kPhotosAddOnly = 3,
  kLocation = 4,
  kLocationAlways = 5,
  kLocationWhenInUse = 6,
  kNotification = 7,
  kContacts = 8,
  kContactsReadOnly = 9,
  kContactsWriteOnly = 10,
  kCalendar = 11,
  kCalendarReadOnly = 12,
  kCalendarWriteOnly = 13,
  kReminders = 14,
  kStorage = 15,
  kStorageReadOnly = 16,
  kStorageWriteOnly = 17,
  kBluetooth = 18,
  kSpeech = 19,
  kMediaLibrary = 20,
  kSensors = 21,
  kPhone = 22,
  kSms = 23,
  kAppTrackingTransparency = 24,
  kCriticalAlerts = 25,
  kVideos = 26,
  kAudio = 27
};

// Mirror of `PermissionStatus` from `permission_plus_platform_interface`.
enum class PermissionStatusMessage {
  kNotDetermined = 0,
  kGranted = 1,
  kDenied = 2,
  kPermanentlyDenied = 3,
  kRestricted = 4,
  kLimited = 5,
  kProvisional = 6
};

// Mirror of `LocationAccuracy` from `permission_plus_platform_interface`.
enum class LocationAccuracyMessage {
  kReduced = 0,
  kPrecise = 1
};


// Represents a single entry in a permission → status map.
//
// Used for returning results from [requestPermissions], since Pigeon
// does not support `Map` with enum keys directly.
//
// Generated class from Pigeon that represents data sent in messages.
class PermissionStatusMapEntry {
 public:
  // Constructs an object setting all fields.
  explicit PermissionStatusMapEntry(
    const PermissionTypeMessage& permission,
    const PermissionStatusMessage& status);

  const PermissionTypeMessage& permission() const;
  void set_permission(const PermissionTypeMessage& value_arg);

  const PermissionStatusMessage& status() const;
  void set_status(const PermissionStatusMessage& value_arg);

  bool operator==(const PermissionStatusMapEntry& other) const;
  bool operator!=(const PermissionStatusMapEntry& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
 private:
  static PermissionStatusMapEntry FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class PermissionPlusHostApi;
  friend class PigeonInternalCodecSerializer;
  PermissionTypeMessage permission_;
  PermissionStatusMessage status_;
};


class PigeonInternalCodecSerializer : public ::flutter::StandardCodecSerializer {
 public:
  PigeonInternalCodecSerializer();
  inline static PigeonInternalCodecSerializer& GetInstance() {
    static PigeonInternalCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const ::flutter::EncodableValue& value,
    ::flutter::ByteStreamWriter* stream) const override;
 protected:
  ::flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    ::flutter::ByteStreamReader* stream) const override;
};

// Host API implemented in C++, called from Dart.
//
// Generated interface from Pigeon that represents a handler of messages from Flutter.
class PermissionPlusHostApi {
 public:
  PermissionPlusHostApi(const PermissionPlusHostApi&) = delete;
  PermissionPlusHostApi& operator=(const PermissionPlusHostApi&) = delete;
  virtual ~PermissionPlusHostApi() {}
  // Checks the current status of [permission] without triggering a request.
  virtual void CheckPermission(
    const PermissionTypeMessage& permission,
    std::function<void(ErrorOr<PermissionStatusMessage> reply)> result) = 0;
  // Requests [permission] from the user.
  virtual void RequestPermission(
    const PermissionTypeMessage& permission,
    std::function<void(ErrorOr<PermissionStatusMessage> reply)> result) = 0;
  // Requests multiple [permissions] at once.
  virtual void RequestPermissions(
    const ::flutter::EncodableList& permissions,
    std::function<void(ErrorOr<::flutter::EncodableList> reply)> result) = 0;
  // Opens the platform's app settings page.
  virtual void OpenSettings(std::function<void(ErrorOr<bool> reply)> result) = 0;
  // Whether the platform recommends showing a rationale before requesting
  // [permission].
  //
  // Always returns `false` on Windows.
  virtual void ShouldShowRationale(
    const PermissionTypeMessage& permission,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  // Gets the current location accuracy level.
  virtual void GetLocationAccuracy(std::function<void(ErrorOr<LocationAccuracyMessage> reply)> result) = 0;
  // Requests temporary precise location access.
  //
  // Not applicable on Windows — returns the current location status.
  virtual void RequestTemporaryPreciseLocation(
    const std::string& purpose_key,
    std::function<void(ErrorOr<PermissionStatusMessage> reply)> result) = 0;

  // The codec used by PermissionPlusHostApi.
  static const ::flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `PermissionPlusHostApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    PermissionPlusHostApi* api);
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    PermissionPlusHostApi* api,
    const std::string& message_channel_suffix);
  static ::flutter::EncodableValue WrapError(std::string_view error_message);
  static ::flutter::EncodableValue WrapError(const FlutterError& error);
 protected:
  PermissionPlusHostApi() = default;
};
}  // namespace permission_plus_windows
#endif  // PIGEON_PERMISSION_PLUS_API_G_H_
