name: permission_plus_windows
description: "Windows implementation of the permission_plus plugin."

version: 0.1.0

homepage: https://github.com/jagadeeshchoudhary/permission_plus_windows
repository: https://github.com/jagadeeshchoudhary/permission_plus_windows/tree/main
issue_tracker: https://github.com/jagadeeshchoudhary/permission_plus_windows/issues

environment:
  sdk: ^3.12.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.18.0
  permission_plus_platform_interface: ^0.1.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  pigeon: ^26.3.4

flutter:
  plugin:
    platforms:
      windows:
        dartPluginClass: PermissionPlusWindows
        pluginClass: PermissionPlusWindowsPluginCApi

topics:
  - permissions
  - windows
  - plugin
